//product constants
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL"

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"

//category constants
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_FAIL = "GET_CATEGORY_LIST_FAIL"

//auth constants
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const SIGNUP = "SIGNUP"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const REMOVE_SIGNUP_DATA = "REMOVE_SIGNUP_DATA"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const OTP_VERIFICATION = "OTP_VERIFICATION"
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"
export const OTP_VERIFICATION_FAIL = "OTP_VERIFICATION_FAIL"

export const RESEND_OTP = "RESEND_OTP"

export const CHECK_RESET_PASSWORD_TOKEN_VALIDATION = "CHECK_RESET_PASSWORD_TOKEN_VALIDATION"

export const RESET_PASSWORD = "RESET_PASSWORD"

export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_USER_DETAILS_LOADING = "GET_USER_DETAILS_LOADING"
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL"

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"

export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

export const GET_USER_ADDRESS = "GET_USER_ADDRESS"
export const GET_USER_ADDRESS_LOADING = "GET_USER_ADDRESS_LOADING"
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS"
export const GET_USER_ADDRESS_FAIL = "GET_USER_ADDRESS_FAIL"

export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS"

export const DELETE_ACCOUNT = "DELETE_ACCOUNT"

//category constants
export const GET_CART_ITEMS_LIST = "GET_CART_ITEMS_LIST"
export const GET_CART_ITEMS_LIST_SUCCESS = "GET_CART_ITEMS_LIST_SUCCESS"
export const GET_CART_ITEMS_LIST_FAIL = "GET_CART_ITEMS_LIST_FAIL"

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL"

export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const DELETE_ITEM_FROM_CART_SUCCESS = "DELETE_ITEM_FROM_CART_SUCCESS"
export const DELETE_ITEM_FROM_CART_FAIL = "DELETE_ITEM_FROM_CART_FAIL"

export const INCREASE_CART_COUNT = "INCREASE_CART_COUNT"
export const DECREASE_CART_COUNT = "DECREASE_CART_COUNT"
export const CLEAR_CART_COUNT = "CLEAR_CART_COUNT"

export const CREATE_ORDER = "CREATE_ORDER"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const GET_MY_ORDERS = "GET_MY_ORDERS"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL"

export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS"
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS"
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL"

export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"

export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"

export const CANCEL_ORDER = "CANCEL_ORDER"
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL"

export const ADD_UPDATE_REVIEWS = "ADD_UPDATE_REVIEWS"
export const ADD_UPDATE_REVIEWS_SUCCESS = "ADD_UPDATE_REVIEWS_SUCCESS"
export const ADD_UPDATE_REVIEWS_FAIL = "ADD_UPDATE_REVIEWS_FAIL"

export const DELETE_REVIEW = "DELETE_REVIEW"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"